### ISSUE TITLE
request

### ISSUE THREAD

**Issue by gospodinBezkrai** [Factual0367/Break-Down-Walls#2]
Thanks, just installed the extension and did first tests. Looks very neat!

feature requests:
It would be great if it could be activated by a keyboard shortcut. I am already using alt+Q with BibItNow to be adding the papers to my ref manager. An alt+1 (or something) to get the pdf too would be amazing!

Could you also add a setting to open scihub in the same tab, rather than a new one? Then, after saving it, I could use my usual backspace workflow to go back to journal site and google search.

Thanks loads! <3

**Comment by Factual0367** [comment]
Thanks for the suggestions. I implemented them, you can update the extension to use them. You can find how to change the keyboard shortcut in the README. 

Please report back if you find any issues.
